name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: 
          zip -r release.zip . \
          -x "node_modules/*" \
          -x ".git/*" \
          -x ".github/*" \

      - uses: azure/webapps-deploy@v3
        with:
          app-name: nutritrack-backend-
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
          package: release.zip